/* Futuristic Science — sample catalog data (research-use-only mock).
   Real pricing: each product has strength variants with vial + box (10-vial) prices.
   `price` = lowest vial price (used for "from" display + filters).
   `size`  = strength range label for cards.
   NOTE: all cards reuse the GHK-CU vial photo — brand supplied only that image.
   No dosing, medical, or human-use copy anywhere. */
(function () {
  const products = [
    { id: 'glow', name: 'GLOW', subtitle: 'Peptide Blend', category: 'Dermal Research',
      featured: true, inStock: true, purity: '99.3%', batch: 'FUTURE-CN-MARK-GLOW-0701-001',
      image: '../../assets/vial-glow-70mg.png',
      blurb: 'A multi-peptide research blend supplied as lyophilized powder for in-vitro laboratory research.',
      components: [
        ['BPC-157', '15 amino acids · 1,419 Da'],
        ['TB-500', '43 amino acids · 4,963 Da'],
        ['GHK-Cu', '3 amino acids + Cu²⁺ · 403 Da'],
      ],
      references: [
        { source: 'Tydes Research', title: 'GLOW Peptide Blend: GHK-Cu, TB-500, and BPC-157 in Regenerative Research', year: '2025', url: '#' },
        { source: 'International Journal of Molecular Sciences', title: 'Regenerative and Protective Actions of the GHK-Cu Peptide in the Light of the New Gene Data', year: '2018', meta: 'PMID: 29986520', authors: 'Pickart L, Margolina A', url: 'https://pubmed.ncbi.nlm.nih.gov/29986520/' },
        { source: 'Nature Scientific Reports', title: 'Thymosin Beta 4 and Cardiac Repair', year: '2017', authors: 'Chi NC et al.', url: 'https://pubmed.ncbi.nlm.nih.gov/?term=thymosin+beta+4+cardiac+repair' },
        { source: 'Current Pharmaceutical Design', title: 'BPC 157 and Standard Angiogenic Growth Factors. Gastrointestinal Tract Healing, Lessons from Tendon, Ligament, Muscle and Bone Healing', year: '2018', meta: 'PMID: 30101703', authors: 'Seiwerth S et al.', url: 'https://pubmed.ncbi.nlm.nih.gov/30101703/' },
        { source: 'Journal of Molecular Medicine', title: 'BPC-157 Interacts with the Nitric Oxide System', year: '2016', authors: 'Hsieh MJ et al.', url: 'https://pubmed.ncbi.nlm.nih.gov/?term=BPC-157+nitric+oxide' },
        { source: 'Cell and Tissue Research', title: 'Gastric Pentadecapeptide Body Protection Compound BPC 157 and Its Role in Accelerating Musculoskeletal Soft Tissue Healing', year: '2019', meta: 'PMID: 30915550', authors: 'Gwyer D et al.', url: 'https://pubmed.ncbi.nlm.nih.gov/30915550/' },
        { source: 'Growth Hormone & IGF Research', title: 'BPC-157 Upregulates Growth Hormone Receptor Expression', year: '2018', url: 'https://pubmed.ncbi.nlm.nih.gov/?term=BPC-157+growth+hormone+receptor' },
        { source: 'Journal of Investigative Dermatology', title: 'Thymosin Beta-4 Accelerates Wound Healing', year: '1999', meta: 'PMID: 10594747', authors: 'Malinda KM et al.', url: 'https://pubmed.ncbi.nlm.nih.gov/10594747/' },
        { source: 'Cosmetics', title: 'The Human Tripeptide GHK and Tissue Remodeling', year: '2015', authors: 'Pickart L et al.', url: 'https://pubmed.ncbi.nlm.nih.gov/?term=GHK+tissue+remodeling+Pickart' },
        { source: 'Multiple Sources', title: 'Individual Peptide Research Literature', url: 'https://pubmed.ncbi.nlm.nih.gov/?term=research+peptides' },
      ],
      variants: [
        { strength: '70mg', vial: 65, box: 360 },
      ] },
    { id: 'retatrutide', name: 'RETA-3', subtitle: 'Triple Receptor Peptide', category: 'Metabolic Research',
      featured: true, inStock: true, purity: '99.2%', batch: 'FUTURE-CN-MARK-RETA-0701-001',
      image: '../../assets/vial-reta-3.png',
      blurb: 'A synthetic multi-receptor peptide supplied as lyophilized powder for in-vitro laboratory research.',
      variants: [
        { strength: '10mg', vial: 50, box: 225 },
        { strength: '20mg', vial: 75, box: 360 },
        { strength: '30mg', vial: 100, box: 440 },
      ] },
    { id: 'tirzepatide', name: 'TIRZ-2', subtitle: 'Dual Receptor Peptide', category: 'Metabolic Research',
      featured: true, inStock: true, purity: '99.1%', batch: 'FUTURE-CN-MARK-TIRZ-0701-001',
      image: '../../assets/vial-tirz-2.png',
      blurb: 'A synthetic dual-receptor peptide supplied for laboratory research applications.',
      variants: [
        { strength: '10mg', vial: 55, box: 325 },
        { strength: '20mg', vial: 75, box: 400 },
        { strength: '30mg', vial: 100, box: 425 },
      ] },
    { id: 'ghk-cu', name: 'GHK-Cu', subtitle: 'Copper Tripeptide', category: 'Dermal Research',
      featured: true, inStock: true, purity: '99.4%', batch: 'FUTURE-CN-MARK-GHKC-0701-001',
      blurb: 'A copper-binding tripeptide studied in laboratory research. Supplied as lyophilized powder for in-vitro investigation.',
      variants: [
        { strength: '50mg', vial: 30, box: 115 },
        { strength: '100mg', vial: 45, box: 140 },
      ] },
    { id: 'bpc-157', name: 'BPC-157', subtitle: 'Body Protection Compound', category: 'Tissue Repair Research',
      featured: true, inStock: true, purity: '99.1%', batch: 'FUTURE-CN-MARK-BPCC-0701-001',
      image: '../../assets/vial-bpc-157.png',
      blurb: 'A synthetic peptide fragment used as a reference compound in laboratory research settings.',
      variants: [
        { strength: '5mg', vial: 20, box: 120 },
        { strength: '10mg', vial: 40, box: 205 },
      ] },
    { id: 'tb-500', name: 'TB-500', subtitle: 'Thymosin Beta-4 Fragment', category: 'Tissue Repair Research',
      inStock: true, purity: '99.6%', batch: 'FUTURE-CN-MARK-THYM-0701-001',
      image: '../../assets/vial-tb-500.png',
      blurb: 'A synthetic fragment supplied as lyophilized powder for qualified in-vitro research.',
      variants: [
        { strength: '5mg', vial: 27, box: 250 },
        { strength: '10mg', vial: 40, box: 290 },
      ] },
    { id: 'mots-c', name: 'MOTS-c', subtitle: 'Mitochondrial Peptide', category: 'Cellular Research',
      inStock: true, purity: '99.3%', batch: 'FUTURE-CN-MARK-MOTS-0701-001',
      image: '../../assets/vial-mots-c.png',
      blurb: 'A mitochondrial-derived peptide studied in laboratory research.',
      variants: [
        { strength: '10mg', vial: 45, box: 200 },
        { strength: '20mg', vial: 55, box: 340 },
      ] },
    { id: 'selank', name: 'Selank', subtitle: 'Heptapeptide', category: 'Neuro Research',
      inStock: true, purity: '99.2%', batch: 'FUTURE-CN-MARK-SELA-0701-001',
      image: '../../assets/vial-selank.png',
      blurb: 'A synthetic heptapeptide used as a research reference compound.',
      variants: [
        { strength: '5mg', vial: 25, box: null },
        { strength: '10mg', vial: 40, box: 195 },
      ] },
    { id: 'semax', name: 'Semax', subtitle: 'Heptapeptide', category: 'Neuro Research',
      inStock: true, purity: '99.2%', batch: 'FUTURE-CN-MARK-SEMA-0701-001',
      image: '../../assets/vial-semax.png',
      blurb: 'A synthetic peptide investigated in laboratory research. For in-vitro use only.',
      variants: [
        { strength: '5mg', vial: 30, box: null },
        { strength: '10mg', vial: 40, box: 300 },
      ] },
    { id: 'nad-plus', name: 'NAD+', subtitle: 'Coenzyme', category: 'Circadian Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-NADP-0701-001',
      image: '../../assets/vial-nad-plus.png',
      blurb: 'A coenzyme supplied as lyophilized powder for laboratory research applications.',
      variants: [
        { strength: '100mg', vial: 35, box: null },
        { strength: '500mg', vial: 45, box: null },
        { strength: '1000mg', vial: 75, box: 575 },
      ] },
    { id: 'tesamorelin', name: 'Tesamorelin', subtitle: 'GHRH Analog', category: 'Secretagogue Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-TESA-0701-001',
      image: '../../assets/vial-tesamorelin.png',
      blurb: 'A synthetic peptide supplied for laboratory research applications.',
      variants: [
        { strength: '5mg', vial: 45, box: 300 },
        { strength: '10mg', vial: 65, box: 375 },
      ] },
    { id: 'klow', name: 'KLOW', subtitle: 'Peptide Blend', category: 'Tissue Repair Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-KLOW-0701-001',
      image: '../../assets/vial-klow.png',
      blurb: 'A multi-peptide research blend supplied as lyophilized powder for qualified in-vitro research.',
      variants: [
        { strength: '80mg', vial: 75, box: 385 },
      ] },
    { id: 'survodutide', name: 'Survodutide', subtitle: 'Dual Receptor Peptide', category: 'Metabolic Research',
      inStock: true, purity: '99.1%', batch: 'FUTURE-CN-MARK-SURV-0701-001',
      image: '../../assets/vial-survodutide.png',
      blurb: 'A synthetic dual-receptor peptide supplied as lyophilized powder for in-vitro laboratory research.',
      variants: [ { strength: '10mg', vial: 60, box: 360 } ] },
    { id: 'aod-9604', name: 'AOD-9604', subtitle: 'hGH Fragment', category: 'Metabolic Research',
      inStock: true, purity: '99.2%', batch: 'FUTURE-CN-MARK-AOD9-0701-001',
      image: '../../assets/vial-aod-9604.png',
      blurb: 'A synthetic peptide fragment supplied for qualified in-vitro research.',
      variants: [ { strength: '10mg', vial: 45, box: 250 } ] },
    { id: 'lipo-c', name: 'LIPO-C', subtitle: 'Lipotropic Blend', category: 'Metabolic Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-LIPC-0701-001',
      image: '../../assets/vial-lipo-c.png',
      blurb: 'A lipotropic research blend supplied in solution for in-vitro laboratory research.',
      variants: [ { strength: '10ml', vial: 40, box: 280 } ] },
    { id: 'l-carnitine', name: 'L-Carnitine', subtitle: 'Amino Acid Derivative', category: 'Metabolic Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-LCAR-0701-001',
      image: '../../assets/vial-l-carnitine.png',
      blurb: 'An amino acid derivative supplied in solution for laboratory research applications.',
      variants: [ { strength: '10ml', vial: 30, box: 180 } ] },
    { id: 'ipamorelin', name: 'Ipamorelin', subtitle: 'Growth Hormone Secretagogue', category: 'Secretagogue Research',
      inStock: true, purity: '99.3%', batch: 'FUTURE-CN-MARK-IPAM-0701-001',
      image: '../../assets/vial-ipamorelin.png',
      blurb: 'A synthetic pentapeptide supplied as lyophilized powder for qualified in-vitro research.',
      variants: [ { strength: '10mg', vial: 35, box: 200 } ] },
    { id: 'sermorelin', name: 'Sermorelin', subtitle: 'GHRH Analog', category: 'Secretagogue Research',
      inStock: true, purity: '99.1%', batch: 'FUTURE-CN-MARK-SERM-0701-001',
      image: '../../assets/vial-sermorelin.png',
      blurb: 'A synthetic peptide supplied for laboratory research applications.',
      variants: [ { strength: '10mg', vial: 35, box: 200 } ] },
    { id: 'cjc-1295', name: 'CJC-1295 w/o DAC', subtitle: 'GHRH Analog', category: 'Secretagogue Research',
      inStock: true, purity: '99.2%', batch: 'FUTURE-CN-MARK-CJCN-0701-001',
      image: '../../assets/vial-cjc-1295.png',
      blurb: 'A synthetic peptide supplied as lyophilized powder for qualified in-vitro research.',
      variants: [ { strength: '5mg + 5mg', vial: 45, box: 250 } ] },
    { id: 'igf-1lr3', name: 'IGF-1LR3', subtitle: 'Growth Factor Analog', category: 'Secretagogue Research',
      inStock: true, purity: '98.8%', batch: 'FUTURE-CN-MARK-IGFL-0701-001',
      image: '../../assets/vial-igf-1lr3.png',
      blurb: 'A synthetic growth factor analog supplied for qualified in-vitro research.',
      variants: [ { strength: '.1mg', vial: 55, box: 360 } ] },
    { id: 'kisspeptin-10', name: 'KissPeptin-10', subtitle: 'Decapeptide', category: 'Secretagogue Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-KISS-0701-001',
      image: '../../assets/vial-kisspeptin-10.png',
      blurb: 'A synthetic decapeptide used as a research reference compound.',
      variants: [ { strength: '10mg', vial: 45, box: 250 } ] },
    { id: 'epithalon', name: 'Epithalon', subtitle: 'Tetrapeptide', category: 'Cellular Research',
      inStock: true, purity: '99.2%', batch: 'FUTURE-CN-MARK-EPIT-0701-001',
      image: '../../assets/vial-epithalon.png',
      blurb: 'A synthetic tetrapeptide studied in laboratory research.',
      variants: [ { strength: '10mg', vial: 40, box: 220 } ] },
    { id: 'cartalax', name: 'Cartalax', subtitle: 'Peptide Bioregulator', category: 'Cellular Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-CART-0701-001',
      image: '../../assets/vial-cartalax.png',
      blurb: 'A synthetic peptide bioregulator supplied as lyophilized powder for in-vitro research.',
      variants: [ { strength: '20mg', vial: 45, box: 240 } ] },
    { id: 'glutathione', name: 'Glutathione', subtitle: 'Antioxidant Tripeptide', category: 'Cellular Research',
      inStock: true, purity: '99.4%', batch: 'FUTURE-CN-MARK-GLUT-0701-001',
      image: '../../assets/vial-glutathione.png',
      blurb: 'A tripeptide antioxidant supplied as lyophilized powder for laboratory research.',
      variants: [ { strength: '1500mg', vial: 50, box: 320 } ] },
    { id: 'ss-31', name: 'SS-31', subtitle: 'Mitochondrial Peptide', category: 'Cellular Research',
      inStock: true, purity: '99.1%', batch: 'FUTURE-CN-MARK-SS31-0701-001',
      image: '../../assets/vial-ss-31.png',
      blurb: 'A synthetic mitochondria-targeting peptide studied in laboratory research.',
      variants: [ { strength: '10mg', vial: 55, box: 340 } ] },
    { id: 'kpv', name: 'KPV', subtitle: 'Tripeptide', category: 'Tissue Repair Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-KPVX-0701-001',
      image: '../../assets/vial-kpv.png',
      blurb: 'A synthetic tripeptide used as a research reference compound.',
      variants: [ { strength: '10mg', vial: 35, box: 190 } ] },
    { id: 'ara-290', name: 'ARA-290', subtitle: 'Erythropoietin Derivative', category: 'Tissue Repair Research',
      inStock: true, purity: '99.1%', batch: 'FUTURE-CN-MARK-ARA2-0701-001',
      image: '../../assets/vial-ara-290.png',
      blurb: 'A synthetic peptide supplied as lyophilized powder for qualified in-vitro research.',
      variants: [ { strength: '10mg', vial: 50, box: 300 } ] },
    { id: 'wolverine', name: 'TB/BPC Wolverine', subtitle: 'Peptide Blend', category: 'Tissue Repair Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-WOLV-0701-001',
      image: '../../assets/vial-wolverine.png',
      blurb: 'A multi-peptide research blend supplied as lyophilized powder for in-vitro laboratory research.',
      variants: [ { strength: '10mg + 10mg', vial: 70, box: 400 } ] },
    { id: 'ahk-cu', name: 'AHK-Cu', subtitle: 'Copper Tripeptide', category: 'Dermal Research',
      inStock: true, purity: '99.2%', batch: 'FUTURE-CN-MARK-AHKC-0701-001',
      image: '../../assets/vial-ahk-cu.png',
      blurb: 'A copper-binding tripeptide studied in laboratory research. Supplied as lyophilized powder for in-vitro investigation.',
      variants: [ { strength: '100mg', vial: 40, box: 150 } ] },
    { id: 'mt-2', name: 'MT-2', subtitle: 'Melanocortin Peptide', category: 'Dermal Research',
      inStock: true, purity: '99.0%', batch: 'FUTURE-CN-MARK-MT2X-0701-001',
      image: '../../assets/vial-mt-2.png',
      blurb: 'A synthetic melanocortin peptide supplied as lyophilized powder for qualified in-vitro research.',
      variants: [ { strength: '10mg', vial: 30, box: 160 } ] },
  ];

  // Derive `price` (min vial) and `size` (strength range label) for each product.
  products.forEach((p) => {
    p.price = Math.min(...p.variants.map((v) => v.vial));
    const s = p.variants.map((v) => v.strength);
    p.size = s.length === 1 ? s[0] : `${s[0]}–${s[s.length - 1]}`;
  });

  window.FS_DATA = {
    contact: {
      email: 'FuturisticScienceUSA@gmail.com',
      phone: '920-265-2896',
      company: 'Futuristic Science, LLC',
    },
    categories: ['Tissue Repair Research', 'Dermal Research', 'Metabolic Research', 'Secretagogue Research', 'Cellular Research', 'Neuro Research', 'Circadian Research'],
    products,
    image: '../../assets/vial-ghk-cu.png',
  };
})();
